version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpwd
    volumes:
      - ./_mongodb:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped
